
--ROLLBACK;

--DROP FUNCTION delete_post(integer,integer);

CREATE OR REPLACE FUNCTION delete_post (_id INT , _user_id INT) RETURNS posts AS
$BODY$
DECLARE
	deleted_post	posts%ROWTYPE ;
BEGIN
	DELETE
	FROM		posts
	WHERE		id = _id
	RETURNING	*
	INTO STRICT	deleted_post
	;
	
	IF deleted_post.user_id != _user_id
	THEN
		RAISE 'User ID --> % is not the owner of post ID --> %' , _user_id , _id ;
	END IF ;
	
	RETURN	deleted_post ;
EXCEPTION
	WHEN NO_DATA_FOUND THEN RAISE NO_DATA_FOUND USING MESSAGE = 'Nonexistent post ID --> %' || _id ;
END ;
$BODY$
LANGUAGE plpgsql ;

--BEGIN;
--SELECT * FROM delete_post( 14 , 8 );
--COMMIT;
--ROLLBACK ;
