version: "3"


services:
  
  backend:

    depends_on:
      - db

    #build: .  # Not supposed to build in prod

    #image: your-user-name/your-fast-api-app

    image: my-fastapi-app
    
    ports:
      - 8000:8000
    
    env_file:
      - ./.env
  

  db:

    image: postgres:alpine
    
    env_file:
      - ./.env

    #environment:
    #  - POSTGRES_PASSWORD=${ POSTGRES_PASSWORD }
    
    volumes:
      - postgres:/var/lib/postgresql/data


  reverse-proxy:

    depends_on:
      - backend

    build: tmp-config

    ports:
      - 8080:80



volumes:

  postgres:

