version: "3"


services:
  
  backend:

    depends_on:
      - db

    build:
      dockerfile: tests/Dockerfile
      context: .
    
    ports:
      - 9000:8000
    
    env_file:
      - .env.intgr

    volumes:
      - .:/opt/app

    command: uvicorn app.main:app  --host 0.0.0.0  --port 8000  --reload
    # -s  to see print statements
    #pytest --verbose -s --disable-warnings --exitfirst
  

  db:

    image: postgres:alpine

    ports:
      - 5434:5432
    
    env_file:
      - .env.intgr
    
    volumes:
      - postgres-testing:/var/lib/postgresql/data



volumes:

  postgres-testing:

